<?php
	header( 'Content-type: text/javascript' );
	include "jquery.js";
	include "ui.base.js";
	include "ui.draggable.js";
	include "ui.droppable.js";
	include "jquery.dimensions.js";
	include "modal.js";
	include "trivial/dates.js";
	include "coala.js";
	include "album/list.js";
	include "album/photo/list.js";
	include "album/photo/view.js";
	include "notification/view.js";
	include "poll/list.js";
	include "poll/view.js";
	include "journal/list.js";
	include "journal/view.js";
	include "journal/new.js";
	include "user/join.js";
	include "user/joined.js";
	include "user/settings.js";
	include "user/profile.js";
	include "space/space.js";
	include "banner.js";
	include "pm.js";
	include "frontpage.js";
    include "moodpicker.js";
	include "settings.js";
	include "types.js";
    include "questions.js";
	include "wysiwyg.js";
	include "browsers_allowed.js";
?>
